services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  worker:
    build: ./worker
    depends_on:
      - rabbitmq

  notifier:
    build: ./notifier
    depends_on:
      - rabbitmq
